### ISSUE TITLE
Replace 'Gasoline' term with 'Petrol' based on their location.

### ISSUE THREAD

**Issue by boro741** [OiWorld/CarbonFootprint#128]
As in India also in some countries like UK Gasoline is referred as Petrol.
So replacing the term  based on their location  would ease people in understanding.
![screen shot 2016-12-04 at 11 26 13 pm](https://cloud.githubusercontent.com/assets/16509376/20868143/2a331c64-ba7a-11e6-9314-421b49243b70.png)

**Comment by Ceilican** [comment]
That's a great idea!

Are you planning to implement it?

**Comment by boro741** [comment]
Yeah I'm planning for it.

**Comment by Ceilican** [comment]
Ok. Thanks! Here are some tips:

1) I think it is better to make the fuel name depend on the user's "language/locale" preferences, rather than his/her location. For example, if the user has "en-UK" as his locale, he would still prefer to see "petrol" instead of "gasoline", even if he is currently located in the US.

2) @PrateekGupta1509 created a mechanism to allow internationalization/localization of the options page based on locales. Please use his mechanism.

Good luck!

**Comment by boro741** [comment]
Thanks! That's a great hint for me to start.

**Comment by boro741** [comment]
![screen shot 2016-12-29 at 8 55 24 pm](https://cloud.githubusercontent.com/assets/16509376/21547011/4c0cd274-ce09-11e6-8905-f9eac0b6c8c5.png)

Now I would be allowing petrol to display when the user selects Imperial and Gasoline when they select the US.

And for a metric should I keep both?

**Comment by ceilican** [comment]
Hi @boro741 ! Thanks for the screenshot. I like how it is looking. Maybe we should simply keep both "Petrol" and "Gasoline" as options independently of what the unit system chosen by the user?

**Comment by boro741** [comment]
I've added Petrol to the list. But I don't know what broken when the map is opened it doesn't automatically pop-up on a new tab.

Here's the [link I made changes to the file](https://github.com/boro741/CarbonFootprint/commit/c600bc1e99cd8f2d9502ac0a9bbff3df7c53d707).

**Comment by boro741** [comment]
ok got it. Thank you @Kolpa

**Comment by boro741** [comment]
[Solution to this PR](https://github.com/OiWorld/CarbonFootprint/pull/129)

**Comment by ceilican** [comment]
Thanks!
